import { createRoot } from "react-dom/client";

const root = document.getElementById("root");
if (root) {
  createRoot(root).render(
    <div style={{ fontFamily: "system-ui", padding: 24 }}>
      <h1>__PROJECT_NAME__</h1>
      <p>Generated by ViteForge.</p>
    </div>
  );
}
